### PR TITLE
Eflumerf/styleguide conformance

### LINKED ISSUE #20: non_cost getter
Hi just caught this method of fragment that is non cost getter

https://github.com/DUNE-DAQ/dataformats/blob/ba3784872729191cc57c149f47ed77697a831b2d/include/dataformats/Fragment.hpp#L123

### PR DESCRIPTION
**Pull request by eflumerf**
Resolves #20, as well as ensuring compliance with the new member variable naming rules in the style guide.

### CODE REVIEW

**Comment by eflumerf** [comment]
This pull request contains changes from and therefor obsoletes PR #19

**Comment by eflumerf** [comment]
Please correct me if I'm wrong, and the styleguide may need additional updates, but I thought the trailing underscore was still used for private members (as opposed to the struct members which have public visibility).

**Comment by jcfreeman2** [comment]
Do *NOT* merge this into the develop branch until further notice, as this introduces interface changes which break code in packages which depend on this one.

**Review by bieryAtFnal — APPROVED** [review]
These changes have been examined by several people, and have been verified to run correctly in a simple test of a partial minidaqapp.

**Pull request merged**
