### PR TITLE
Adding format for raw WIB TP frame

### PR DESCRIPTION
**Pull request by hristovaivana**
Added a TP dataformat for parsing TP data by the FakeCardReader module.

### CODE REVIEW

**Comment by roland-sipos** [comment]
The PR name is not representing the actual content. Please update it.

**Review by roland-sipos — CHANGES_REQUESTED** [review]
I think the main idea was to name the file `WIBTPFrame`. (As it's not compatible with PD TPs, which is not even discussed yet.) In it's current form it can confuse people.

Otherwise, as v1 it's fine with me.

**Comment by roland-sipos** [comment]
I just realized, that the PR also does not comply with the code conventions. @hristovaivana please have a look on the member fields of the WIBFrame, and make the required modifications. (e.g.: "m_" prefixed member fields.)

Details about the coding conventions can be found under:
https://github.com/DUNE-DAQ/styleguide/blob/develop/dune-daq-cppguide.md

**Comment by philiprodrigues** [comment]
> I think the main idea was to name the file `WIBTPFrame`. (As it's not compatible with PD TPs, which is not even discussed yet.) In it's current form it can confuse people.

We might also want the name to avoid possible confusion with the TP format used in the data selection system. Maybe `RawWIBTP...`?

There's a nontrivial change that I think needs to be made: as I understand it, the idea is to persist these classes via the `dunedaq` `Fragment` class. `Fragment` requires its data payload to be contiguous in memory, but `TPDataBlock` has a `std::vector` member. The content of `std::vector` is stored elsewhere on the heap, so it's not contiguous in memory with the `TPDataBlock`. One ugly way to get around this is by using a "flexible array member", as demonstrated here:

https://cdcvs.fnal.gov/redmine/projects/dune-raw-data/repository/entry/dune-raw-data/Overlays/CPUHitsFragment.hh?rev=feature%2Fper-message-roi-online

Alternatively, you can just have getters that calculate the appropriate offsets (possibly using `offsetof`).

The other thing that I think would be useful to add is a unit test. I think the most useful thing would be to check that an existing TP frame (which you could hardcode in the test) is correctly decoded by the code here.

**Comment by roland-sipos** [comment]
I agree with @philiprodrigues to rename it to `RawWIBTP`. If we find anything better later, we do it on the same go when we move these bitfields.

Unit test -> Really good point, yes please! Like there is one for the WIBFrame:
https://github.com/DUNE-DAQ/dataformats/blob/develop/unittest/WIBFrame_test.cxx

On the nontrivial changes:
- But the dunedaq `Fragment` is capable of scatter-gather creation though, right? So a `Fragment` creator function in the TP class is sufficient to hand over the "list" of `TPDataBlock` pointers? I don't think the "overlay" like classes should do anything related to memory. If the sizes are dynamic, it's some utility that needs to serialize it to a continuous memory block (E.g.: Fragment) to another destination on the stack. Maybe this needs a discussion on Slack, rather than here.

**Comment by philiprodrigues** [comment]
>     * But the dunedaq `Fragment` is capable of scatter-gather creation though, right? So a `Fragment` creator function in the TP class is sufficient to hand over the "list" of `TPDataBlock` pointers? I don't think the "overlay" like classes should do anything related to memory. If the sizes are dynamic, it's some utility that needs to serialize it to a continuous memory block (E.g.: Fragment) to another destination on the stack. Maybe this needs a discussion on Slack, rather than here. Seems like the enforcement of "RawDataTypes to become Fragments" is needed, maybe via an interface? ( `WIBFrame : public UserPayload` where `UserPayload` must implement `createFragment` ? )

I was assuming that the `TPFrame` that comes out of the firmware is _already_ contiguous in memory. If that's the case, then the idea of the overlay class would be to be able to write:

```cpp
TPFrame* frame=reinterpret_cast<TPFrame*>(block_of_memory);
TPData* tp=frame->get_tp(3); // or whatever
```

WIth this, the offline processing can do the same, just that now `block_of_memory` is the payload bytes from a `Fragment`.

If you use the gather ctor of `Fragment` to serialize a non-contiguous set of memory areas into a `Fragment`, then you have to have decoding code that's kept in sync with the code that calls the `Fragment` ctor. That's doable, of course, but it would be extra code in addition to the overlay class.

**Comment by roland-sipos** [comment]
Hi @philiprodrigues . Really good points above, we definitely have an eye on this.
Meanwhile I also realized that probably we should do the split of the raw decoders to it's dedicated package (which already exists, just empty.). @hristovaivana  will continue to develop this locally on readout. I'm closing the PR without merge now.

**Comment by hristovaivana** [comment]
Hi Phil and Roland,
Thanks for the comments and discussion to this PR. While working on them, we decided to move temporarily the raw WIB 
TP format development to the 'readout' repository where is it being immediately used while also developing the fake TP readout
at the same time.
When this it is ready, we are going to move the raw WIB TP .hpp format file back to the 'dataformats' repository. I am working 
on the unittest and we should also decide on removing the usage of vector for the purpose of serialization.
Thanks!
Ivana

**Pull request closed without merging**
